trigger:
- master

variables:
  imageRepository: 'jpetstore-6'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build
    jobs:
    - job: Build
      steps:
      - task: Maven@3
        displayName: 'Maven pom.xml'
        inputs:
          mavenPomFile: 'pom.xml'
          codeCoverageToolOption: Cobertura
          checkStyleRunAnalysis: true
          pmdRunAnalysis: true
          findBugsRunAnalysis: true


      - task: Docker@2
        displayName: Build
        inputs:
          command: buildAndPush
          repository: $(imageRepository)
          dockerfile: $(dockerfilePath)
          containerRegistry: acr3939
          tags: |
            $(tag)
